### ISSUE TITLE
does the remote mapping using the .hwdb file work for you?

### ISSUE THREAD

**Issue by cenright** [benjaminmetzler/OpenRemoteHub#12]
I have tried, and it doesn't seem to work for me

evtest  still outputs code 240 (KEY_UNKNOWN)

the mappings show on the input using udevadm info

I am using the latest raspberry pi os 64bit with desktop,  think I should try the old 32bit lite version you used?
=============
well, I tried a different remote and remapping works.  The only difference I can see is that the one that doesn't work shows up as virtual and is bluetooth / the working one looks like a 'real' USB keyboard ?

this mapping that doesn't work

udevadm info /dev/input/event2
P: /devices/virtual/misc/uhid/0005:0471:1208.0002/input/input5/event2
N: input/event2
L: 0
E: DEVPATH=/devices/virtual/misc/uhid/0005:0471:1208.0002/input/input5/event2
E: DEVNAME=/dev/input/event2
E: MAJOR=13
E: MINOR=66
E: SUBSYSTEM=input
E: USEC_INITIALIZED=24731908
E: KEYBOARD_KEY_c0037=zoomin
E: KEYBOARD_KEY_c0038=stop
E: KEYBOARD_KEY_c0049=stop
E: KEYBOARD_KEY_c004a=!playpause
E: KEYBOARD_KEY_c01c8=3
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_BUS=bluetooth
E: XKBMODEL=pc105
E: XKBLAYOUT=us
E: BACKSPACE=guess
E: LIBINPUT_DEVICE_GROUP=5/471/1208:b8:27:eb:65:24:47
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:

This does:

udevadm info /dev/input/event4
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:4842:0001.0003/input/input7/event4
N: input/event4
L: 0
S: input/by-path/platform-3f980000.usb-usb-0:1.3:1.2-event-kbd
S: input/by-id/usb-HAOBO_Technology_USB_Composite_Device_1120030400060623-if02-event-kbd
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:4842:0001.0003/input/input7/event4
E: DEVNAME=/dev/input/event4
E: MAJOR=13
E: MINOR=68
E: SUBSYSTEM=input
E: USEC_INITIALIZED=112436208430
E: KEYBOARD_KEY_c00cd=3
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_BUS=usb
E: ID_MODEL=USB_Composite_Device
E: ID_MODEL_ENC=USB\x20Composite\x20Device
E: ID_MODEL_ID=0001
E: ID_SERIAL=HAOBO_Technology_USB_Composite_Device_1120030400060623
E: ID_SERIAL_SHORT=1120030400060623
E: ID_VENDOR=HAOBO_Technology
E: ID_VENDOR_ENC=HAOBO\x20Technology
E: ID_VENDOR_ID=4842
E: ID_REVISION=0100
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Composite_Device
E: ID_USB_MODEL_ENC=USB\x20Composite\x20Device
E: ID_USB_MODEL_ID=0001
E: ID_USB_SERIAL=HAOBO_Technology_USB_Composite_Device_1120030400060623
E: ID_USB_SERIAL_SHORT=1120030400060623
E: ID_USB_VENDOR=HAOBO_Technology
E: ID_USB_VENDOR_ENC=HAOBO\x20Technology
E: ID_USB_VENDOR_ID=4842
E: ID_USB_REVISION=0100
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:010100:010200:030001:
E: ID_USB_INTERFACE_NUM=02
E: ID_USB_DRIVER=usbhid
E: ID_PATH=platform-3f980000.usb-usb-0:1.3:1.2
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_3_1_2
E: XKBMODEL=pc105
E: XKBLAYOUT=us
E: BACKSPACE=guess
E: LIBINPUT_DEVICE_GROUP=3/4842/1:usb-3f980000.usb-1
E: DEVLINKS=/dev/input/by-path/platform-3f980000.usb-usb-0:1.3:1.2-event-kbd /dev/input/by-id/usb-HAOBO_Technology_USB_Composite_Device_1120030400060623-if02-event-kbd
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:

**Comment by benjaminmetzler** [comment]
Take a look at the Unknown Scancodes section of https://github.com/benjaminmetzler/OpenRemoteHub/blob/main/documentation/new_remotes.md. I ran into a unknown key presses that gave a 240 code as well.

**Comment by cenright** [comment]
Yes - I did, your instructions were good, I was able to isolate the issue to a specific remote -> it works fine for another type I had.
However, I haven't figure out why the remote I want to use does not work.  In the meantime, I am hacking up the code to work with the 'unrecognized scan codes' read from evdev, so I can move forward.

**Comment by benjaminmetzler** [comment]
Interesting. Which remote are you using?

**Comment by cenright** [comment]
My remote is nothing special / it's a tivo android bluetooth remote.  When I connect it to the pi, it gets registered a 'virtual keyboard'. 

 DEVPATH=/devices/virtual/misc/uhid/0005:0471:1208.0002/input/input5/event2

I am wanting to turn it into a 'universal' remote. I found your project here / looks like you've already got a good framework going / thank you sir.

**Comment by benjaminmetzler** [comment]
Is it a specific button on the remote that has an issue or is it the entire remote doesn't work? I haven't tried with a Bluetooth remote. It could be something fundamentally different between a USB and a Bluetooth keyboard that's causing the issue.

**Comment by cenright** [comment]
It's about 5 or 6 buttons that don't map on it / the rest are good.  You can consider the issue closed, since it's specific to a single instance of remote.  Thanks for the project and for looking though.

I've gotten past this issue => I forked and made it substitute the actual raw scancode and it works fine for my purposes.
